/*
 * Workflow Execution Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.dfornika.ga4ghwes.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * A message that allows one to describe default parameters for a workflow engine.
 */
@Schema(description = "A message that allows one to describe default parameters for a workflow engine.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T18:04:40.054Z[GMT]")public class DefaultWorkflowEngineParameter {

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("default_value")
  private String defaultValue = null;
  public DefaultWorkflowEngineParameter name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * The name of the parameter
  * @return name
  **/
  @Schema(description = "The name of the parameter")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public DefaultWorkflowEngineParameter type(String type) {
    this.type = type;
    return this;
  }

  

  /**
  * Describes the type of the parameter, e.g. float.
  * @return type
  **/
  @Schema(description = "Describes the type of the parameter, e.g. float.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public DefaultWorkflowEngineParameter defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

  

  /**
  * The stringified version of the default parameter. e.g. \&quot;2.45\&quot;.
  * @return defaultValue
  **/
  @Schema(description = "The stringified version of the default parameter. e.g. \"2.45\".")
  public String getDefaultValue() {
    return defaultValue;
  }
  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DefaultWorkflowEngineParameter defaultWorkflowEngineParameter = (DefaultWorkflowEngineParameter) o;
    return Objects.equals(this.name, defaultWorkflowEngineParameter.name) &&
        Objects.equals(this.type, defaultWorkflowEngineParameter.type) &&
        Objects.equals(this.defaultValue, defaultWorkflowEngineParameter.defaultValue);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(name, type, defaultValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DefaultWorkflowEngineParameter {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
